apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: resilient-app
data:
  NODE_ENV: "production"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "resilient_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: resilient-app
type: Opaque
stringData:
  DB_USER: "dbadmin"
  DB_PASSWORD: "SuperSecurePassword123!"
  REDIS_PASSWORD: ""
